config/routes.rb
Tweeter::Application.routes.draw do
  root "tweets#index"

  resources :tweets, only: [:new, :create, :show]
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  validates :body, length: 5..1000
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @query = params[:query]

    @tweets = Tweet.order('created_at DESC')
    if @query.present?
      @tweets = @tweets.where('body like?', "%#{@query}%")
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)

    if @tweet.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:author, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweeter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/index.html.erb
<h1>Tweeter</h1>
<div>
<%= link_to 'Post a Tweet', new_tweet_path %><%= form_tag root_path, method: :get do %>
</div>
<div>
  <%= text_field_tag :query, @query, placeholder: 'Search for...' %><%= submit_tag "Search" %>
<% end %>
</div><br />

<% @tweets.each do |tweet| %>
<div>
</div>
<div>
  @<strong><%= tweet.author.downcase %></strong>
  <%= highlight(simple_format(word_wrap(truncate(tweet.body, length: 80) { link_to "(read more)", tweet })), @query) %>
  Date: <%= tweet.created_at.getlocal.strftime("%D") %><br />
  Length: <%= pluralize(tweet.body.length, "character") %>
</div><br />
<% end %>

app/views/tweets/new.html.erb
<h1>Post a New Tweet</h1>
<%= form_for @tweet do |f| %>

<div>
  <%= f.label :author, "Your Name" %>
  <%= f.text_field :author %>
</div>
<div>
  <%= f.label :body, "Your Message" %>
  <%= f.text_field :body %>
</div>
<div>
  <%= f.submit "Post Tweet" %>
</div>
<% end %>

app/views/tweets/show.html.erb
<h1><%= @tweet.author %>'s Tweet</h1>
<div>
  <table>
    <tr>
      <td>
          <%= link_to '< all tweets', root_path %>
      </td>
      <td>
      </td>
    </tr>
    <tr>
      <td>
        <%= @tweet.created_at.getlocal.strftime("%D at %-I:%M %P:") %>
      </td>
      <td>
      </td>
    </tr>
  </table>
</div><br />
<div>
  <%= @tweet.body %>
</div>